### ISSUE TITLE
Pls add favicon - currently blank

### ISSUE THREAD

**Issue by jpat125** [Mount-Albert-Grammar-School/magsschol#6]
![image](https://github.com/Mount-Albert-Grammar-School/magsschol/assets/106706305/2940b3e5-a3a6-4dbd-97cb-607c4eb7ba70)

**Comment by Sseptimus** [comment]
do it yourself

**Comment by jpat125** [comment]
Ok, pls give access

https://www.w3schools.com/html/html_favicon.asp

**Comment by jpat125** [comment]
Jaiden currently working on.

**Comment by jpat125** [comment]
Completed (w/ slight bit of help from Anatol)

<img width="54" alt="Screenshot 2023-05-12 181753" src="https://github.com/Mount-Albert-Grammar-School/magsschol/assets/106706305/037f0ef5-2245-4b0f-be40-a42fdb28b3ff">
